source "https://rubygems.org"

# Use the latest Jekyll instead of the legacy "github-pages" gem
# This is required for Ruby 3.2+ compatibility.
gem "jekyll", "~> 4.3.3"
gem "minima", "~> 2.5"

# Plugins
gem "jekyll-seo-tag"
gem "jekyll-feed"

# Core dependencies removed in recent Ruby versions
gem "webrick"
gem "csv"
gem "base64"
gem "mutex_m"
gem "logger"
gem "bigdecimal"
